name: Build, Test, Package

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**.csproj'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ master ]

jobs:     
  ubuntu-test:
    runs-on: ubuntu-latest  
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
    - uses: actions/checkout@v2
    - name: Caching
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/*.csproj') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-
    - name: Setup .NET Sdk
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
            8.x
    - name: Test .NET 8
      run: dotnet test -v normal -f net8.0 --logger "console;verbosity=detailed" --nologo /nologo      
      
  upload-packages:
    needs: [ubuntu-test] 
    if: success()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Caching
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/*.csproj') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-
    - name: Setup .NET Sdk
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'
    - name: Publish Nuget Package
      uses: alirezanet/publish-nuget@v3.1.0
      with:
        PROJECT_FILE_PATH: src/ProxySourceGenerator/ProxySourceGenerator.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        TAG_FORMAT: v*
